### ISSUE TITLE
没有指定调到哪页的api

### ISSUE THREAD

**Issue by bbhuang01** [SimonZhangITer/light-swiper#1]

**Comment by SimonZhangITer** [comment]
感谢反馈
原先是有这个Api的，但是在部分场景下存在bug，就没有放出这个Api。
目前我发布了一个新版本`1.0.2`开放了这个Api，使用方法为

```javascript
slide(toIndex, speed)
```
但需要注意的是，在`continue`模式下存在bug，其余场景应该没有问题
